---
name: jekyll
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  jekyll:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: bundle exec jekyll build
